### ISSUE TITLE
Modelling non-pharmaceutical treatments.

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#226]
How should we model non-pharmaceutical treatments? e.g. radiotherapy, immunotherapy, phototherapy, oxygen administration... Currently we have:

```proto
// medication, procedure, other actions taken for clinical management
message MedicalAction {
    oneof action {
        PharmaceuticalTreatment pharmaceutical_treatment = 1;
        Procedure procedure = 2;
        // (to be expanded....)
    }
}

// treatment with a pharmaceutical agent
message PharmaceuticalTreatment {
    OntologyClass drug = 1;  // for instance, DrugCentral, RxNorm Drugbank concept
    OntologyClass route_of_administration = 2; // For instance, NCIT subhierarchy: Route of Administration (Code C38114)
    repeated DoseInterval dose_intervals  = 3;
    DrugType drug_type = 4;
    StopReason stop_reason_id = 5; // TODO: What if this is still ongoing? Will need a new value for this.
}
```
`PharmaceuticalTreatment` does not quite fit other treatments. There is a `Procedure` message, but this doesn't quite fit as, we already have the concept of a Procedure, which is used in Biosample:

```proto
message Biosample {
    // other fields...

    // Clinical procedure performed on the subject in order to extract the biosample.
    Procedure procedure = 13;
}

// A clinical procedure performed on a subject. By preference a single concept to indicate both the procedure and the
// body site should be used. In cases where this is not possible, the body site should be indicated using a separate
// ontology class.
// e.g.
// {"code":{"NCIT:C51585": "Biopsy of Soft Palate"}}
// {"code":{"NCIT:C28743": "Punch Biopsy"}, "body_site":{"UBERON:0003403": "skin of forearm"}} - a punch biopsy of the skin from the forearm
// FHIR mapping: Procedure (https://www.hl7.org/fhir/procedure.html)
message Procedure {
    // FHIR mapping: Procedure.code
    OntologyClass code = 1;
    // FHIR mapping: Procedure.bodySite
    OntologyClass body_site = 2;
    // When the procedure was performed.
    TimeElement performed = 3;
}
```

For example in the COVID-19 use case:

https://github.com/phenopackets/phenopacket-schema/blob/79ec508cc9d7ad8d90293283fda66a98ef0c1f59/src/test/java/org/phenopackets/schema/v1/examples/CovidExample.java#L113-L142

Here the patient was treated with Oxygen, had Hydroxychloroquine administered and later required tracheal intubation.

One thing which could be useful would be to add an 'outcome' field to the medical action. For example, in this case the overall combinations of medical actions were unsuccessful and the patient died. Here, perhaps the `medicalActions` should be linked with a disease. e.g. the fitting of the `Left Ventricular Assist Device` was in response to the `Cardiomyopathy`. The rest of the 'medicalAction`s were in response to the COVID-19.

Below is the YAML representation of the patient's treatment history:

```yaml
medicalActions:
# This was in response to the diagnosis of Cardiomyopathy 
- procedure:
    code:
      id: "NCIT:C80473"
      label: "Left Ventricular Assist Device"
    performed:
      timestamp: "2016-01-01T00:00:00Z"
# These were taken in response to the COVID-19 symptoms:
- pharmaceuticalTreatment:
    drug:
      id: "NCIT:C722"
      label: "Oxygen"
    routeOfAdministration:
      id: "NCIT:C38284"
      label: "Nasal Route of Administration"
    doseIntervals:
    - quantity:
        unit:
          id: "NCIT:C67388"
          label: "Liter per Minute"
        value: 2.0
      interval:
        start: "2020-03-20T00:00:00Z"
        end: "2020-03-22T00:00:00Z"
    - quantity:
        unit:
          id: "NCIT:C67388"
          label: "Liter per Minute"
        value: 50.0
      interval:
        start: "2020-03-22T00:00:00Z"
        end: "2020-03-23T00:00:00Z"
- pharmaceuticalTreatment:
    drug:
      id: "NCIT:C557"
      label: "Hydroxychloroquine"
    doseIntervals:
    - interval:
        start: "2020-03-20T00:00:00Z"
        end: "2020-03-22T00:00:00Z"
    stopReasonId: "REMOVED"
- procedure:
    code:
      id: "NCIT:C116648"
      label: "Tracheal Intubation"
    performed:
      timestamp: "2020-03-22T00:00:00Z"
- pharmaceuticalTreatment:
    drug:
      id: "NCIT:C722"
      label: "Oxygen"
    routeOfAdministration:
      id: "NCIT:C50254"
      label: "Positive end Expiratory Pressure Valve Device"
    doseIntervals:
    - quantity:
        unit:
          id: "NCIT:C91060"
          label: "Centimeters of Water"
        value: 14.0
      interval:
        start: "2020-03-22T00:00:00Z"
        end: "2020-03-28T00:00:00Z"
- pharmaceuticalTreatment:
    drug:
      id: "NCIT:C84217"
      label: "Tocilizumab"
    doseIntervals:
    - interval:
        start: "2020-03-24T00:00:00Z"
        end: "2020-03-28T00:00:00Z"

```
