### ISSUE TITLE
Rename Age.age to Age.iso8601

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-schema#254]
Currently Age has a single 'age' field which is a string type. This seems fine, however it reads badly in the new `TimeElement` message and isn't indicative to the user what the field is supposed to represent.

```proto
message Age {
    // The :ref:`ISO 8601<metadata_date_time>` age of this object as ISO8601
    // duration or time intervals. The use of time intervals makes an additional
    // anchor unnecessary (i.e. DOB and age can be represented as start-anchored
    // time interval, e.g. 1967-11-21/P40Y10M05D)
    string age = 1;
}
```

I would like to propose the field `age` be renamed `iso8601`

```proto
message Age {
    // The :ref:`ISO 8601<metadata_date_time>` age of this object as ISO8601
    // duration or time intervals. The use of time intervals makes an additional
    // anchor unnecessary (i.e. DOB and age can be represented as start-anchored
    // time interval, e.g. 1967-11-21/P40Y10M05D)
    string iso8601 = 1;
}
```

In situ, this would result in the following:

```yaml
subject:
  id: "kindred 1A"
  dateOfBirth: "1998-01-01T00:00:00Z"
  sex: "MALE"
  ageAtCollection:
    age:
      iso8601: "P3Y"
```
as opposed to 

```yaml
subject:
  id: "kindred 1A"
  dateOfBirth: "1998-01-01T00:00:00Z"
  sex: "MALE"
  ageAtCollection:
    age:
      age: "P3Y"
```
